choco install --confirm googlechrome
choco install --confirm winrar
choco install --confirm adobereader
choco install --confirm flashplayerplugin
choco install --confirm firefox
choco install --confirm opera-gx
choco install --confirm jre8
choco install --confirm vcredist140
choco install --confirm adobeair
choco install --confirm microsoft-teams.install
choco install --confirm notepadplusplus.install
choco install --confirm vcredist2015
choco install --confirm dotnetfx
choco install --confirm vlc
choco install --confirm silverlight
choco install --confirm zoom
choco install --confirm foxitreader
choco install --confirm ccleaner
choco install --confirm libreoffice-fresh
choco install --confirm anydesk
choco install --confirm ultravnc
choco install --confirm cpu-z